In [1]:
import torch 
print(torch.__version__) 

import torchvision
print(torchvision.__version__)  

1.10.0+cpu
0.11.1+cu102


In [2]:
x = torch.Tensor(3,2)
print(x)

x = torch.empty(3,2)
print(x)

x = torch.rand(3,4)
print(x)

tensor([[0.0000e+00, 1.0469e-38],
        [2.1067e-07, 1.0617e+21],
        [8.2730e+20, 1.7377e-04]])
tensor([[2.6330e+20, 1.0573e-05],
        [1.3613e-05, 8.2270e+20],
        [1.3457e+22, 2.5667e-09]])
tensor([[0.2363, 0.3151, 0.2951, 0.3839],
        [0.6942, 0.4312, 0.2008, 0.8001],
        [0.9635, 0.4362, 0.9528, 0.9736]])


In [3]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
x = torch.ones(2,2,requires_grad=True)
print(x)
print(x.grad_fn)
y = x+2
print(y,y.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>) <AddBackward0 object at 0x0000023D9556C9B0>


In [5]:
z = y*y*3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [6]:
print(x)
q = x*x
out = q.mean()
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])
