In [1]:
import numpy as np
d = np.zeros((5,5))
print(d)
def longestCommonSubsequence(x,y):
    m = len(x)
    n = len(y)
    c = [[0] * (n) for _ in range(m)] # dp数组
    b = [[0] * (n) for _ in range(m)] # 用来标记打印情况的
    for i in range(1,m):
        for j in range(1,n): # 根据递推公式如下
            if x[i] == y[j]:
                c[i][j] = c[i-1][j-1]+1
                b[i][j] = 1
            elif c[i-1][j]>=c[i][j-1]:
                c[i][j] = c[i-1][j]
                b[i][j] = 2
            else:
                c[i][j] = c[i][j-1]
                b[i][j] = 3
    return c,b 


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [2]:
def PRINT_LCS(b,X,i,j):
    if i==0 or j==0:
        return
    if b[i][j] == 1:
        PRINT_LCS(b,X,i-1,j-1)
        print(X[i-1])
    elif b[i][j] == 2:
        PRINT_LCS(b,X,i-1,j)
    elif b[i][j] == 3:
        PRINT_LCS(b,X,i,j-1)


In [3]:
x = "abcdefea"
y = "aceadad"

x = " "+x
y = " "+y
c,d = longestCommonSubsequence(x,y)
for i in d:
    print(i)
print(x[1:])
PRINT_LCS(d,x[1:],len(x)-1,len(y)-1)


[0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 3, 3, 1, 3, 1, 3]
[0, 2, 2, 2, 2, 2, 2, 2]
[0, 2, 1, 3, 3, 3, 3, 3]
[0, 2, 2, 2, 2, 1, 3, 1]
[0, 2, 2, 1, 3, 2, 2, 2]
[0, 2, 2, 2, 2, 2, 2, 2]
[0, 2, 2, 1, 2, 2, 2, 2]
[0, 1, 2, 2, 1, 3, 1, 3]
abcdefea
a
c
d
a
