In [69]:
import numpy as np


In [70]:
x = np.array(10)
print(x,'dim=',x.ndim,x.shape)

10 dim= 0 ()


In [71]:
y =  np.array([1,2,3,4,5])
print(y,'dim=',y.ndim,y.shape,y.shape[0])

[1 2 3 4 5] dim= 1 (5,) 5


In [72]:
x = np.array([[1,2],[3,4]])
y = np.ones((3,2,2))
print(y)
print(x+y)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[[2. 3.]
  [4. 5.]]

 [[2. 3.]
  [4. 5.]]

 [[2. 3.]
  [4. 5.]]]


In [73]:
def countPrimes(n):
       def countPrimes(n):
        """
        :type n: int
        :rtype: int
        """
        s = []
        for i in range(n):
            s.append(0)
        for i in range(2,n):
            if s[i] == 1 :
                continue
            for j in range(i,n):
                if i*j<n:
                    s[i*j] = 1
        for i in range(n):
            print(i,s[i])
        count = 0
        for i in range(2,n):
            if s[i]==0:
                count +=1
        return count


countPrimes(10)

In [74]:
def findRelativeRanks(score):
        """
        :type score: List[int]
        :rtype: List[str]
        """
        l = []
        for i in range(40):
            l.append(-1)
        j = 0
        for i in score:
            l[i] = j
            j += 1
        k = []
        j = 0
        print(l)
        for i in l:
            # if i == len(score)-1:
            #     k.append("Gold Medal")
            # elif i==len(score)-2:

            #     k.append("Silver Medal")
            # elif i==len(score)-3:
        
            #     k.append("Bronze Medal")
            if i==-1:
                continue
            else:
                k.append(i)
        p = []   
        for i in range(len(k)):
            p.append(0)
        le = len(k)
        j=0
        for i in k:
            p[i] = le-j
            j+=1
        print(p)
        for i in range(le):
            if p[i] == 1:
                p[i]="Gold Medal"
                print(i)
            elif p[i]==2:
                p[i]="Silver Medal"
            elif p[i]==3:
                p[i]="Bronze Medal"
            else:
                p[i] = str(p[i])
        print(p)
        return k
l = [5,30,2,1,3]
findRelativeRanks(l)

[-1, 3, 2, 4, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
[2, 1, 4, 5, 3]
1
['Silver Medal', 'Gold Medal', '4', '5', 'Bronze Medal']


[3, 2, 4, 0, 1]