In [219]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

In [220]:
#导入数据集

train_data = pd.read_csv("D:\Mis\project\python\dataMine\data\data_train.csv")
test_data = pd.read_csv("D:\Mis\project\python\dataMine\data\data_test.csv")
print("The shape of train_data", train_data.shape)
print("The shape of test_data", test_data.shape)


The shape of train_data (1298, 12)
The shape of test_data (301, 12)


In [221]:
train_data.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1298.000000       1298.000000  1298.000000     1298.000000   
mean        8.563713          0.519503     0.287565        2.562635   
std         1.765711          0.177694     0.196394        1.307516   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.300000          0.390000     0.110000        1.900000   
50%         8.200000          0.500000     0.280000        2.200000   
75%         9.500000          0.630000     0.450000        2.600000   
max        15.900000          1.330000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1298.000000          1298.000000           1298.000000  1298.000000   
mean      0.088678            15.521572             46.835901     0.996954   
std       0.047607            10.378344             33.548496     0.001897   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.071000             7.000000             21.250000     0.995860   
50%       0.080000            13.000000             38.000000     0.996940   
75%       0.092000            21.000000             63.000000     0.998010   
max       0.611000            72.000000            289.000000     1.003200   

                pH    sulphates      alcohol      quality  
count  1298.000000  1298.000000  1298.000000  1298.000000  
mean      3.299869     0.663544    10.406471     5.661787  
std       0.154522     0.174552     1.095820     0.810744  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.200000     0.560000     9.500000     5.000000  
50%       3.300000     0.620000    10.100000     6.000000  
75%       3.390000     0.730000    11.100000     6.000000  
max       3.900000     2.000000    14.900000     8.000000

In [222]:
train_data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [223]:
train_data=np.array(train_data)
test_data=np.array(test_data)

In [224]:
def getData(dataSet):
    m, n = np.shape(dataSet)
    trainData = np.ones((m, n-1))
    trainData[:,:-1] = dataSet[:,:-2]
    trainLabel = dataSet[:,-1]
    return trainData, trainLabel

In [225]:
def normalize(X):
    m, n = X.shape
    # 归一化每一个特征
    for j in range(n):
        features = X[:,j]
        minVal = features.min(axis=0)
        maxVal = features.max(axis=0)
        diff = maxVal - minVal
        if diff != 0:
            X[:,j] = (features-minVal)/diff
        else:
            X[:,j] = 0
    return X

In [226]:
def batchGradientDescent(x, y, theta, alpha, m, maxIterations):
    
    xTrains = normalize(x).transpose()
    ylabels=(y-min(y))/(max(y)-min(y))
    for i in range(0, maxIterations):
        hypothesis = np.dot(x, theta)
        loss = hypothesis - ylabels
        gradient = np.dot(xTrains, loss) / m
        theta = theta - alpha * gradient
    return theta

In [227]:
trainFeature, trainLabel = getData(train_data)
m, n = np.shape(trainFeature)
theta = np.ones(n)
alpha = 0.05

array([0., 0., 0., ..., 0., 0., 1.])

In [228]:
theta = batchGradientDescent(trainFeature, trainLabel, theta, alpha, m, 1000)

In [248]:
theta

array([ 0.35137134,  0.13231828,  0.24698665,  0.54279238,  0.45872649,
        0.09733225,  0.1229315 , -0.30957669,  0.40460971,  0.45835376,
        1.        ])

In [247]:
ylabels=(trainLabel-min(trainLabel))/(max(trainLabel)-min(trainLabel))

In [231]:
ylabels

array([0.4, 0.4, 0.4, ..., 0.4, 0.4, 0.6])

In [232]:
def predict(x, theta):
    m, n = np.shape(x)
    xTest = np.ones((m, n))
    xTest[:, :] = x
    yPre = np.dot(xTest, theta)
    return yPre

In [233]:
y_pre=predict(trainFeature, theta)
y_pre

array([0.41199963, 0.46890561, 0.43853724, ..., 0.46946833, 0.46946833,
       0.48899141])

In [234]:
a=sum(y_pre-ylabels)**2
a

230.5179685630983

In [235]:
print(max(trainLabel))
print(min(trainLabel))

8.0
3.0


In [236]:
for i in  range(0,1298):
    if trainLabel[i]>=6:
        trainLabel[i]=1
    else:
        trainLabel[i]=0
trainLabel

array([0., 0., 0., ..., 0., 0., 1.])

In [237]:
y_pre=y_pre*5+3

In [238]:
for i in  range(0,1298):
    if y_pre[i]>=6:
        y_pre[i]=1
    else:
        y_pre[i]=0
y_pre

array([0., 0., 0., ..., 0., 0., 0.])

In [239]:
count=0
for i in  range(0,1298):
    if y_pre[i]==trainLabel[i]:
        count=count+1
count

659

In [240]:
#开始测试
testFeature, testLabel = getData(test_data)


In [241]:
y_pre=predict(normalize(testFeature), theta)
y_pre

array([0.42944236, 0.58715416, 0.54784055, 0.67813313, 0.66262138,
       0.70191596, 0.46747663, 0.54254181, 0.71808748, 0.52036844,
       0.71808748, 0.46173146, 0.54254181, 0.52792561, 0.56773607,
       0.5364434 , 0.5457304 , 0.56390764, 0.62219269, 0.71271245,
       0.56390764, 1.37850812, 0.72143681, 0.6012153 , 0.56875866,
       0.7168676 , 0.52054518, 0.52054518, 0.52054518, 0.52054518,
       0.39489548, 0.55771664, 0.55771664, 0.62639293, 0.31498608,
       0.50289738, 0.51192532, 0.53001568, 0.29003916, 0.29003916,
       0.29003916, 0.44111994, 0.44111994, 0.44111994, 0.43251231,
       0.44111994, 0.61325374, 0.46734322, 0.40898044, 0.32095474,
       0.32095474, 0.48208254, 0.65029041, 0.46290767, 0.42247017,
       0.42247017, 0.41661678, 0.38915916, 0.38350668, 0.65070527,
       0.75925356, 0.66217384, 0.60959521, 0.56611667, 0.66217384,
       0.52469015, 0.49279292, 0.4688992 , 0.41900048, 0.80176811,
       0.55633517, 0.2857118 , 1.26625703, 0.92512375, 1.26625

In [242]:
ylabels=(testLabel-min(testLabel))/(max(testLabel)-min(testLabel))
a=sum(y_pre-ylabels)**2
a

367.0913397456511

In [243]:
for i in  range(0,301):
    if testLabel[i]>=6:
        testLabel[i]=1
    else:
        testLabel[i]=0
trainLabel

array([0., 0., 0., ..., 0., 0., 1.])

In [244]:
y_pre=y_pre*5+3

In [245]:
for i in  range(0,301):
    if y_pre[i]>=6:
        y_pre[i]=1
    else:
        y_pre[i]=0
y_pre

array([0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1.,
       0., 0., 0., 1., 0.

In [246]:
count=0
for i in  range(0,301):
    if y_pre[i]==trainLabel[i]:
        count=count+1
count/301

0.5647840531561462